doctrine:
    dbal:
        dbname:               'sites'
        host:                 'localhost'
        port:                 '3306'
        user:                 'root'
        password:             'password'
        driver:               pdo_mysql
        url:                  'mysql://root:password@127.0.0.1:3306/sites'
